# Generated by Django 4.2.7 on 2024-03-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusPositions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trip_id", models.IntegerField()),
                ("timestamp", models.DateTimeField()),
                ("langitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
            options={
                "db_table": "bus_positions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BusTrip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trip_id", models.IntegerField()),
                ("start_datetime", models.DateTimeField()),
                ("schedule_relationship", models.TextField()),
                ("route_id", models.IntegerField()),
                ("direction_id", models.IntegerField()),
                ("vihecle", models.TextField()),
                ("delay", models.IntegerField()),
            ],
            options={
                "db_table": "bus_trips",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BusRouteShape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route_short_name", models.TextField()),
                ("route_id", models.TextField()),
                ("shape_id", models.TextField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("sequence", models.IntegerField()),
            ],
        ),
    ]
