# Generated by Django 4.2.7 on 2024-03-20 13:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("buses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="busrouteshape",
            options={"managed": False},
        ),
    ]
