# Generated by Django 4.2.7 on 2024-03-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_alter_busrouteshape_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buspositions',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='bustrip',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='busrouteshape',
            table='bus_routes',
        ),
    ]
