# Generated by Django 4.2.7 on 2024-04-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_alter_buspositions_options_alter_bustrip_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buspositions',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='bustrip',
            options={'managed': False},
        ),
    ]
