apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-app
  template:
    metadata:
      labels:
        app: streamlit-app
    spec:
      containers:
      - name: streamlit-app
        image: europe-west4-docker.pkg.dev/scm-group14/scm-container-repository/streamlit-app:latest  # Replace with the actual name and tag of your Streamlit Docker image
        imagePullPolicy: Always
        ports:
        - containerPort: 8501  # The port that Streamlit runs on
